### ISSUE TITLE
Positioning of entities loaded from yml files

### ISSUE THREAD

**Issue by jliersch** [mars-robot-simulation/mars_scene_loader#3]
# Situation
When entites are loaded from yml files, their global position will be twice their defined position due to https://github.com/mars-robot-simulation/mars_scene_loader/blob/b10800e767972d4759603331adeb415e8fe899fb/src/MarsSceneLoader.cpp#L353-L354
The local position of the collision and visual frame will equal the defined position though (see screenshot of entity view below). This local position is used by envire_mars_ode_collision to define the position for the collision items. But envire_mars_graphics (correctly) usese the global position, which leads to an incorrect visualization of primitive objects:

![scene](https://github.com/user-attachments/assets/949a72a7-f511-46ee-8eee-e99d8b5ee15a)
The yellow box in the image has an extend of 1 unit in x and y direction and is centered at the origin. The blue box is defined to be centered at x=0.5, y=0, z=0. Thus it should intersect the yellow box.

![entity_view](https://github.com/user-attachments/assets/0a8d8e88-6015-4d67-bb68-16bdc3660165)
Screenshot from entity view showing the translations set for the blue box.

Fixing the issue for primitive objects, breaks the collision positioning for entities loaded from smurf files. This needs to be investigated.

# Task
* Investigate how the transformations of collisions loaded from smurf files are set in https://github.com/envire/envire-envire_smurf_loader
* Use the global position of frames to set the position of collision items (transformation from root frame instead of parent frame to collision frame in https://github.com/mars-robot-simulation/envire_mars_ode_collision/blob/170c4ea283680a6e03ccc8106b511bd067419171/src/EnvireOdeCollisionPlugins.cpp#L294)
* Correctly set global position of collision objects for entities loaded from .yml files.
* Adapt envire_smurf_loader accordingly

**Comment by haider8645** [comment]
![image](https://github.com/user-attachments/assets/e3b9950f-7ee5-4adb-9471-cbb3821336de)
![image](https://github.com/user-attachments/assets/b0af996d-8664-4217-9d5e-08867f6ab9f7)
![image](https://github.com/user-attachments/assets/4d4d4188-620a-4fb0-a1ad-ee24568f3cd6)
![image](https://github.com/user-attachments/assets/60a1decd-748b-4c29-b405-7efa5b7d4c34)


@jliersch Please find above the respective collision, visual, and smurf loaded from a smurfs file. Is this the behavior you expected?

**Comment by haider8645** [comment]
Create a PR here https://github.com/mars-robot-simulation/mars_scene_loader/pull/4

**Comment by haider8645** [comment]
> Fixing the issue for primitive objects, breaks the collision positioning for entities loaded from smurf files. This needs to be investigated.

I don't understand what is meant by this statement. I tried to load the robot model and the collisions and visuals seem to be loaded properly (see screenshots). Am I missing something?

**Comment by haider8645** [comment]
> When entites are loaded from yml files, their global position will be twice their defined position due to
> 
> https://github.com/mars-robot-simulation/mars_scene_loader/blob/b10800e767972d4759603331adeb415e8fe899fb/src/MarsSceneLoader.cpp#L353-L354

Right, remove these two lines seems to fix the loading!

**Comment by jliersch** [comment]
> > When entites are loaded from yml files, their global position will be twice their defined position due to
> > https://github.com/mars-robot-simulation/mars_scene_loader/blob/b10800e767972d4759603331adeb415e8fe899fb/src/MarsSceneLoader.cpp#L353-L354
> 
> Right, remove these two lines seems to fix the loading!

This fixes the visuals but breaks the positioning of the collision object used for the physics simulation. It seems like the local position of the collision frame is used for this and this is 0,0,0 after the fix. This leads to the behavior below - first image before starting the physics simulation, second shortly after the start. 

![collision_pre_sim_start](https://github.com/user-attachments/assets/c3078388-c961-49e2-9382-45bba9899eff)
![collision_post_sim_start](https://github.com/user-attachments/assets/d1ef0f3a-855a-4411-bab5-e098a101f906)

If I recall correctly, I tried fixing this issue by using the global position of the collision object instead for the physics simulation, but this lead to an explosion of the robotic system as soon as the simulation was started. This lead me to the hunch that loading entites from smurf files was broken after fixing the visual and collision positioning for primitives.

**Comment by jliersch** [comment]
Fixed with 
https://github.com/mars-robot-simulation/mars_scene_loader/pull/4 and https://github.com/mars-robot-simulation/envire_mars_ode_collision/pull/3
Thanks for the fix @haider8645
